/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Checks that the BFF process is up */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/check_apis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Checks that the three upstream BFFs are reachable */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Every upstream BFF answered its /health operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckApisResponse"];
                    };
                };
                /** @description At least one upstream BFF is unreachable or not configured */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckApisResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Data from the same BFFs as the business pages, within the session scope */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardBootstrap"];
                    };
                };
                /** @description Missing or invalid session, or session refused by an upstream BFF */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description User context unavailable: BFF User unreachable, failed or answered an invalid body */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description An upstream BFF is not configured */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /** @enum {string} */
                code: "BAD_REQUEST" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "PAYLOAD_TOO_LARGE" | "UNPROCESSABLE_ENTITY" | "TOO_MANY_REQUESTS" | "INTERNAL_ERROR" | "BAD_GATEWAY" | "SERVICE_UNAVAILABLE" | "GATEWAY_TIMEOUT";
                message: string;
                details: {
                    path?: string;
                    message: string;
                }[];
            };
        };
        CheckApisResponse: {
            /** @enum {string} */
            status: "OK" | "Error";
            /** @enum {string} */
            user_bff: "Connected" | "Unreachable";
            /** @enum {string} */
            project_bff: "Connected" | "Unreachable";
            /** @enum {string} */
            calendar_bff: "Connected" | "Unreachable";
        };
        DashboardBootstrap: {
            userFirstName: string;
            projects: {
                id: string;
                title: string;
                progress: number;
                /** @enum {string} */
                status: "todo" | "in-progress" | "review" | "done";
                dueDate: string;
            }[];
            tasks: {
                id: string;
                title: string;
                dueDate: string;
                /** @enum {string} */
                priority: "high" | "medium" | "low";
                completed: boolean;
                projectId: string;
            }[];
            events: {
                id: string | number;
                title: string;
                date: string;
                startTime?: string;
                location?: string;
            }[];
            metrics: {
                totalProjects: number | null;
            };
            sources: {
                /** @enum {string} */
                projects: "available" | "unavailable";
                /** @enum {string} */
                tasks: "available" | "unavailable";
                /** @enum {string} */
                calendar: "available" | "unavailable";
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
